version: '3.5'

services:
  EventHub_DB_postgres:
    container_name: EventHub_DB_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: "eventhub"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - "5455:5432"
    restart: unless-stopped