version: '3.5'

services:
  EventHub_DB_PostgreSQL:
    container_name: EventHub_DB_PostgreSQL
    image: postgres:16
    environment:
      POSTGRES_DB: "eventhub"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    ports:
      - "5455:5432"
    restart: unless-stopped

  eventhub_app_springboot:
    container_name: EventHub_App_SpringBoot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - EventHub_DB_PostgreSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://EventHub_DB_PostgreSQL:5432/eventhub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    restart: unless-stopped
